from enum import Enum, auto

class DiscordPerm(Enum):
    CREATE_INSTANT_INVITE = auto()
    KICK_MEMBERS = auto()
    BAN_MEMBERS = auto()
    ADMINISTRATOR = auto()
    MANAGE_CHANNELS = auto()
    MANAGE_SERVER = auto()
    ADD_REACTIONS = auto()
    VIEW_AUDIT_LOGS = auto()
    READ_MESSAGES = auto()
    SEND_MESSAGES = auto()
    SEND_TTS_MESSAGES = auto()
    MANAGE_MESSAGES = auto()
    EMBED_LINKS = auto()
    ATTACH_FILES = auto()
    READ_MESSAGE_HISTORY = auto()
    MENTION_EVERYONE = auto()
    EXTERNAL_EMOJIS = auto()
    CONNECT = auto()
    SPEAK = auto()
    MUTE_MEMBERS = auto()
    DEAFEN_MEMBERS = auto()
    MOVE_MEMBERS = auto()
    USE_VOICE_ACTIVATION = auto()
    CHANGE_NICKNAME = auto()
    MANAGE_NICKNAMES = auto()
    MANAGE_ROLES = auto()
    MANAGE_WEBHOOKS = auto()
    MANAGE_EMOJIS = auto()
